# Generated by Django 6.1 on 2026-08-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file_name',
            new_name='model_name',
        ),
    ]
